### ISSUE TITLE
Integrate Travis CI

### ISSUE THREAD

**Issue by robbenti** [radicalbit/flink-jpmml#2]
Integrate Travis CI https://travis-ci.org/

**Comment by maocorte** [comment]
Issue already merged with [PR-5](https://github.com/radicalbit/flink-jpmml/pull/5).
Evaluate before close it if could be interesting create a branch 0.5 (version `0.5.1-SNAPSHOT`) and apply the patch also on it.
cc @robbenti @spi-x-i @francescofrontera
